--------------------------------------------------------------
-- Namespaces
--------------------------------------------------------------
local _, core = ...
core.Source = {}
local Source = core.Source
core.sourceOrder = { 
    'Hearthstones',
    'Class Teleports',
    'Class Portals',
    'Miscellaneous',
    'Challenge Mode Portals - MoP',
    'Challenge Mode Portals - WoD'
}

--------------------------------------------------------------
-- Portals source
--------------------------------------------------------------

Source['Challenge Mode Portals - WoD'] = {
    {id = 159895, type = 'spell', name = 'Path of the Bloodmaul', unobtainable = true},
    {id = 159899, type = 'spell', name = 'Path of the Crescent Moon', unobtainable = true},
    {id = 159896, type = 'spell', name = 'Path of the Iron Prow', unobtainable = true},
    {id = 159900, type = 'spell', name = 'Path of the Dark Rail', unobtainable = true},
    {id = 159901, type = 'spell', name = 'Path of the Verdant', unobtainable = true},
    {id = 159897, type = 'spell', name = 'Path of the Vigilant', unobtainable = true},
    {id = 159898, type = 'spell', name = 'Path of the Skies', unobtainable = true},
    {id = 159902, type = 'spell', name = 'Path of the Burning Mountain', unobtainable = true}
}

Source['Challenge Mode Portals - MoP'] = {
    {id = 131232 , type = 'spell', name = 'Path of the Necromancer', unobtainable = true},
    {id = 131229 , type = 'spell', name = 'Path of the Scarlet Mitre', unobtainable = true},
    {id = 131231 , type = 'spell', name = 'Path of the Scarlet Blade', unobtainable = true},
    {id = 131228 , type = 'spell', name = 'Path of the Black Ox', unobtainable = true},
    {id = 131204 , type = 'spell', name = 'Path of the Jade Serpent', unobtainable = true},
    {id = 131222 , type = 'spell', name = 'Path of the Mogu King', unobtainable = true},
    {id = 131225 , type = 'spell', name = 'Path of the Setting Sun', unobtainable = true},
    {id = 131206 , type = 'spell', name = 'Path of the Shado-Pan', unobtainable = true},
    {id = 131205 , type = 'spell', name = 'Path of the Stout Brew', unobtainable = true}
}

Source['Miscellaneous'] = {
    {id = 64457, type = 'item', name = 'The Last Relic of Argus'},
    {id = 63353, type = 'item', name = 'Shroud of Cooperation', faction = 'Horde'},
    {id = 63207, type = 'item', name = 'Wrap of Unity', faction = 'Horde'},
    {id = 65274, type = 'item', name = 'Cloak of Coordination', faction = 'Horde'},
    {id = 63352, type = 'item', name = 'Shroud of Cooperation', faction = 'Alliance'},
    {id = 63206, type = 'item', name = 'Wrap of Unity', faction = 'Alliance'},
    {id = 65360, type = 'item', name = 'Cloak of Coordination', faction = 'Alliance'},
    {id = 95050, type = 'item', name = 'The Brassiest Knuckle', faction = 'Horde'},
    {id = 92057, type = 'item', name = 'Portal Fuel: Orgrimmar', faction = 'Horde'},
    {id = 95051, type = 'item', name = 'The Brassiest Knuckle', faction = 'Alliance'},
    {id = 92431, type = 'item', name = 'Portal Reagents: Stormwind', faction = 'Alliance'},
    {id = 129929, type = 'toy', name = 'Ever-Shifting Mirror'},
    {id = 18984, type = 'toy', name = 'Dimensional Ripper - Everlook'},
    {id = 18986, type = 'toy', name = 'Ultrasafe Transporter: Gadgetzan'},
    {id = 142469, type = 'item', name = 'Violet Seal of the Grand Magus'},
    {id = 61379, type = 'item', name = 'Gidwin\'s Hearthstone'},
    {id = 37863, type = 'item', name = 'Direbrew\'s Remote'},
    {id = 17909, type = 'item', name =  'Frostwolf Insignia Rank 6', faction = 'Horde',
        prevRank = {id = 17908, type = 'item', name = 'Frostwolf Insignia Rank 5', faction = 'Horde',
        prevRank = {id = 17907, type = 'item', name = 'Frostwolf Insignia Rank 4', faction = 'Horde',
        prevRank = {id = 17906, type = 'item', name = 'Frostwolf Insignia Rank 3', faction = 'Horde',
        prevRank = {id = 17905, type = 'item', name = 'Frostwolf Insignia Rank 2', faction = 'Horde',
        prevRank = {id = 17690, type = 'item', name = 'Frostwolf Insignia Rank 1', faction = 'Horde'}}}}}},
    {id = 17904, type = 'item', name = 'Stormpike Insignia Rank 6', faction = 'Alliance',
        prevRank = {id = 17903, type = 'item', name = 'Stormpike Insignia Rank 5', faction = 'Alliance',
        prevRank = {id = 17902, type = 'item', name = 'Stormpike Insignia Rank 4', faction = 'Alliance',
        prevRank = {id = 17901, type = 'item', name = 'Stormpike Insignia Rank 3', faction = 'Alliance',
        prevRank = {id = 17900, type = 'item', name = 'Stormpike Insignia Rank 2', faction = 'Alliance',
        prevRank = {id = 17691, type = 'item', name = 'Stormpike Insignia Rank 1', faction = 'Alliance'}}}}}},
    {id = 50287, type = 'item', name = 'Boots of the Bay'},
    {id = 63379, type = 'item', name = 'Baradin\'s Wardens Tabard', faction = 'Alliance'},
    {id = 63378, type = 'item', name = 'Hellscream\'s Reach Tabard', faction = 'Horde'},
    {id = 139590, type = 'item', name = 'Scroll of Teleport: Ravenholdt'},
    {id = 52251, type = 'item', name = 'Jaina\'s Locket'},
    {id = 48933, type = 'toy', name = 'Wormhole Generator: Northrend'},
    {id = 46874, type = 'item', name = 'Argent Crusader\'s Tabard'},
    {id = 30544, type = 'toy', name = 'Ultrasafe Transporter: Toshley\'s Station'},
    {id = 30542, type = 'toy', name = 'Dimensional Ripper - Area 52'},
    {id = 32757, type = 'item', name = 'Blessed Medallion of Karabor'},
    {id = 151016, type = 'toy', name = 'Fractured Necrolyte Skull'},
    {id = 58487, type = 'item', name = 'Potion of Deepholm'},
    {id = 87215, type = 'toy', name = 'Wormhole Generator: Pandaria'},
    {id = 92432, type = 'item', name = 'Portal Reagents: Skyfire', faction = 'Alliance'},
    {id = 92056, type = 'item', name = 'Portal Fuel: Sparkrocket Outpost', faction = 'Horde'},
    {id = 95568, type = 'toy', name = 'Sunreaver Beacon', faction = 'Horde'},
    {id = 95567, type = 'toy', name = 'Kirin Tor Beacon', faction = 'Alliance'},
    {id = 103678, type = 'item', name = 'Time-Lost Artifact'},
    {id = 118662, type = 'item', name = 'Bladespire Relic', faction = 'Horde'},
    {id = 118663, type = 'item', name = 'Relic of Karabor', faction = 'Alliance'},
    {id = 168499, type = 'spell', name = 'Home Away from Home', faction = 'Horde'},
    {id = 168487, type = 'spell', name = 'Home Away from Home', faction = 'Alliance'},
    {id = 112059, type = 'toy', name = 'Wormhole Centrifuge'},
    {id = 141605, type = 'item', name = 'Flight Master\'s Whistle'},
    {id = 140493, type = 'item', name = 'Adept\'s Guide to Dimensional Rifting'},
    {id = 129276, type = 'item', name = 'Beginner\'s Guide to Dimensional Rifting'},
    {id = 265225, type = 'spell', name = 'Mole Machine', unobtainable = true},
    {id = 166559, type = 'item', name = 'Commander\'s Signet of Battle', faction = 'Horde'},
    {id = 166560, type = 'item', name = 'Captain\'s Signet of Command', faction = 'Alliance'},
    {id = 43824, type = 'toy', name = 'The Schools of Arcane Magic - Mastery'},
    {id = 144392, type = 'item', name = 'Pugilist\'s Powerful Punching Ring'},
    {id = 21711, type = 'item', name = 'Lunar Festival Invitation'},
    {id = 128502, type = 'item', name = 'Hunter\'s Seeking Crystal'},
    {id = 128503, type = 'item', name = 'Master Hunter\'s Seeking Crystal'},
    {id = 140324, type = 'toy', name = 'Mobile Telemancy Beacon'},
    {id = 22589, type = 'item', name = 'Atiesh, Greatstaff of the Guardian', unobtainable = true},
    {id = 22630, type = 'item', name = 'Atiesh, Greatstaff of the Guardian', unobtainable = true},
    {id = 22631, type = 'item', name = 'Atiesh, Greatstaff of the Guardian', unobtainable = true},
    {id = 22632, type = 'item', name = 'Atiesh, Greatstaff of the Guardian', unobtainable = true},
    {id = 51560, type = 'item', name = 'Runed Band of the Kirin Tor',
        prevRank = {id = 48954, type = 'item', name = 'Etched Band of the Kirin Tor', 
        prevRank = {id = 45688, type = 'item', name = 'Inscribed Band of the Kirin Tor',
        prevRank = {id = 40586, type = 'item', name = 'Band of the Kirin Tor'}}}},
    {id = 51558, type = 'item', name = 'Runed Loop of the Kirin Tor', 
        prevRank = {id = 48955, type = 'item', name = 'Etched Loop of the Kirin Tor',
        prevRank = {id = 45689, type = 'item', name = 'Inscribed Loop of the Kirin Tor',
        prevRank = {id = 44934, type = 'item', name = 'Loop of the Kirin Tor'}}}},
    {id = 51559, type = 'item', name = 'Runed Ring of the Kirin Tor', 
        prevRank = {id = 48956, type = 'item', name = 'Etched Ring of the Kirin Tor', 
        prevRank = {id = 45690, type = 'item', name = 'Inscribed Ring of the Kirin Tor', 
        prevRank = {id = 44935, type = 'item', name = 'Ring of the Kirin Tor'}}}},
    {id = 51557, type = 'item', name = 'Runed Signet of the Kirin Tor',
        prevRank = {id = 48957, type = 'item', name = 'Etched Signet of the Kirin Tor',
        prevRank = {id = 45691, type = 'item', name = 'Inscribed Signet of the Kirin Tor',
        prevRank = {id = 40585, type = 'item', name = 'Signet of the Kirin Tor'}}}},
    {id = 139599, type = 'item', name = 'Empowered Ring of the Kirin Tor'},
    {id = 132119, type = 'item', name = 'Orgrimmar Portal Stone', quest = true},
    {id = 132120, type = 'item', name = 'Stormwind Portal Stone', quest = true},
    {id = 66061, type = 'item', name = 'Bluescale Sigil', quest = true},
    {id = 140319, type = 'item', name = 'Khadgar\'s Beacon', quest = true},
    {id = 35230, type = 'item', name = 'Darnarian\'s Scroll of Teleportation'},
    {id = 167228, type = 'item', name = 'Charm of Returning', quest = true, faction = 'Horde'},
    {id = 141013, type = 'item', name = 'Scroll of Town Portal: Shala\'nir'},
    {id = 141014, type = 'item', name = 'Scroll of Town Portal: Sashj\'tar'},
    {id = 141015, type = 'item', name = 'Scroll of Town Portal: Kal\'delar'},
    {id = 141016, type = 'item', name = 'Scroll of Town Portal: Faronaar'},
    {id = 141017, type = 'item', name = 'Scroll of Town Portal: Lian\'tril'},
    -- 8.2
    {id = 169298, type = 'toy', name = 'Frostwolf Insignia', faction = 'Horde'},
    {id = 169297, type = 'toy', name = 'Stormpike Insignia', faction = 'Alliance'},
    {id = 168808, type = 'toy', name = 'Wormhole Generator: Zandalar'},
    {id = 168807, type = 'toy', name = 'Wormhole Generator: Kul Tiras'},
    {id = 167075, type = 'item', name = 'Ultrasafe Transporter: Mechagon'},
    -- 8.2.5
    {id = 18149, type = 'item', name = 'Rune of Recall', faction = 'Horde', unobtainable = true},
    {id = 18150, type = 'item', name = 'Rune of Recall', faction = 'Alliance', unobtainable = true},
    -- 9.0
    {id = 181163, type = 'item', name = 'Scroll of Teleport: Theater of Pain'},
    {id = 172924, type = 'toy', name = 'Wormhole Generator: Shadowlands'}
}

Source['Class Portals'] = {
    {id = 11417, type = 'spell', name = 'Portal: Orgrimmar', class = 'Mage', faction = 'Horde'},
    {id = 11420, type = 'spell', name = 'Portal: Thunder Bluff', class = 'Mage', faction = 'Horde'},
    {id = 11418, type = 'spell', name = 'Portal: Undercity', class = 'Mage', faction = 'Horde'},
    {id = 49361, type = 'spell', name = 'Portal: Stonard', class = 'Mage', faction = 'Horde'},
    {id = 10059, type = 'spell', name = 'Portal: Stormwind', class = 'Mage', faction = 'Alliance'},
    {id = 11416, type = 'spell', name = 'Portal: Ironforge', class = 'Mage', faction = 'Alliance'},
    {id = 11419, type = 'spell', name = 'Portal: Darnassus', class = 'Mage', faction = 'Alliance'},
    {id = 49360, type = 'spell', name = 'Portal: Theramore', class = 'Mage', faction = 'Alliance'},
    {id = 32267, type = 'spell', name = 'Portal: Silvermoon', class = 'Mage', faction = 'Horde'},
    {id = 32266, type = 'spell', name = 'Portal: Exodar', class = 'Mage', faction = 'Alliance'},
    {id = 120146, type = 'spell', name = 'Ancient Portal: Dalaran', class = 'Mage'},
    {id = 35717, type = 'spell', name = 'Portal: Shattrath', class = 'Mage', faction = 'Horde'},
    {id = 33691, type = 'spell', name = 'Portal: Shattrath', class = 'Mage', faction = 'Alliance'},
    {id = 53142, type = 'spell', name = 'Portal: Dalaran - Northrend', class = 'Mage'},
    {id = 88346, type = 'spell', name = 'Portal: Tol Barad', class = 'Mage', faction = 'Horde'},
    {id = 88345, type = 'spell', name = 'Portal: Tol Barad', class = 'Mage', faction = 'Alliance'},
    {id = 132626, type = 'spell', name = 'Portal: Vale of Eternal Blossoms', class = 'Mage', faction = 'Horde'},
    {id = 132620, type = 'spell', name = 'Portal: Vale of Eternal Blossoms', class = 'Mage', faction = 'Alliance'},
    {id = 176244, type = 'spell', name = 'Portal: Warspear', class = 'Mage', faction = 'Horde'},
    {id = 176246, type = 'spell', name = 'Portal: Stormshield', class = 'Mage', faction = 'Alliance'},
    {id = 224871, type = 'spell', name = 'Portal: Dalaran - Broken Isles', class = 'Mage'},
    {id = 281402, type = 'spell', name = 'Portal: Dazar\'alor', class = 'Mage', faction = 'Horde'},
    {id = 281400, type = 'spell', name = 'Portal: Boralus', class = 'Mage', faction = 'Alliance'},
    {id = 50977, type = 'spell', name = 'Death Gate', class = 'Death Knight'},
    -- 9.0
    {id = 344597, type = 'spell', name = 'Portal: Oribos', class = 'Mage'}
}

Source['Class Teleports'] = {
    {id = 3567, type = 'spell', name = 'Teleport: Orgrimmar', class = 'Mage', faction = 'Horde'},
    {id = 3566, type = 'spell', name = 'Teleport: Thunder Bluff', class = 'Mage', faction = 'Horde'},
    {id = 3563, type = 'spell', name = 'Teleport: Undercity', class = 'Mage', faction = 'Horde'},
    {id = 49358, type = 'spell', name = 'Teleport: Stonard', class = 'Mage', faction = 'Horde'},
    {id = 3561, type = 'spell', name = 'Teleport: Stormwind', class = 'Mage', faction = 'Alliance'},
    {id = 3562, type = 'spell', name = 'Teleport: Ironforge', class = 'Mage', faction = 'Alliance'},
    {id = 3565, type = 'spell', name = 'Teleport: Darnassus', class = 'Mage', faction = 'Alliance'},
    {id = 49359, type = 'spell', name = 'Teleport: Theramore', class = 'Mage', faction = 'Alliance'},
    {id = 32272, type = 'spell', name = 'Teleport: Silvermoon', class = 'Mage', faction = 'Horde'},
    {id = 32271, type = 'spell', name = 'Teleport: Exodar', class = 'Mage', faction = 'Alliance'},
    {id = 120145, type = 'spell', name = 'Ancient Teleport: Dalaran', class = 'Mage'},
    {id = 35715, type = 'spell', name = 'Teleport: Shattrath', class = 'Mage', faction = 'Horde'},
    {id = 33690, type = 'spell', name = 'Teleport: Shattrath', class = 'Mage', faction = 'Alliance'},
    {id = 53140, type = 'spell', name = 'Teleport: Dalaran - Northrend', class = 'Mage'},
    {id = 88344, type = 'spell', name = 'Teleport: Tol Barad', class = 'Mage', faction = 'Horde'},
    {id = 88342, type = 'spell', name = 'Teleport: Tol Barad', class = 'Mage', faction = 'Alliance'},
    {id = 132627, type = 'spell', name = 'Teleport: Vale of Eternal Blossoms', class = 'Mage', faction = 'Horde'},
    {id = 132621, type = 'spell', name = 'Teleport: Vale of Eternal Blossoms', class = 'Mage', faction = 'Alliance'},
    {id = 176242, type = 'spell', name = 'Teleport: Warspear', class = 'Mage', faction = 'Horde'},
    {id = 176248, type = 'spell', name = 'Teleport: Stormshield', class = 'Mage', faction = 'Alliance'},
    {id = 193759, type = 'spell', name = 'Teleport: Hall of the Guardian', class = 'Mage'},
    {id = 224869, type = 'spell', name = 'Teleport: Dalaran - Broken Isle', class = 'Mage'},
    {id = 281404, type = 'spell', name = 'Teleport: Dazar\'alor', class = 'Mage', faction = 'Horde'},
    {id = 281403, type = 'spell', name = 'Teleport: Boralus', class = 'Mage', faction = 'Alliance'},
    {id = 193753, type = 'spell', name = 'Dreamwalk', class = 'Druid', 
        prevRank = {id = 18960, type = 'spell', name = 'Teleport: Moonglade', class = 'Druid'}},
    {id = 136849, type = 'toy', name = 'Nature\'s Beacon', class = 'Druid'},
    {id = 126892, type = 'spell', name = 'Zen Pilgrimage', class = 'Monk'},
    {id = 126896, type = 'spell', name = 'Zen Pilgrimage: Return', class = 'Monk', unobtainable = true},
    -- 9.0
    {id = 344587, type = 'spell', name = 'Teleport: Oribos', class = 'Mage'}
}

Source['Hearthstones'] = {
    {id = 556, type = 'spell', name = 'Astral Recall', class = 'Shaman'},
    {id = 6948, type = 'item', name = 'Hearthstone'},
    {id = 110560, type = 'item', name = 'Garrison Hearthstone'},
    {id = 128353, type = 'item', name = 'Admiral\'s Compass'},
    {id = 140192, type = 'item', name = 'Dalaran Hearthstone'}, 
    {id = 37118, type = 'item', name = 'Scroll of Recall'},
    {id = 44314, type = 'item', name = 'Scroll of Recall II'},
    {id = 44315, type = 'item', name = 'Scroll of Recall III'},
    {id = 162973, type = 'toy', name = 'Greatfather Winter\'s Hearthstone'},
    {id = 165669, type = 'toy', name = 'Lunar Elder\'s Hearthstone'},
    {id = 165670, type = 'toy', name = 'Peddlefeet\'s Lovely Hearthstone'},
    {id = 165802, type = 'toy', name = 'Noble Gardener\'s Hearthstone'},
    {id = 166747, type = 'toy', name = 'Brewfest Reveler\'s Hearthstone'},
    {id = 163045, type = 'toy', name = 'Headless Horseman\'s Hearthstone'},
    {id = 166746, type = 'toy', name = 'Fire Eater\'s Hearthstone'},
    {id = 93672, type = 'toy', name = 'Dark Portal'},
    {id = 54452, type = 'toy', name = 'Ethereal Portal'},
    {id = 64488, type = 'toy', name = 'The Innkeeper\'s Daughter'},
    {id = 142542, type = 'toy', name = 'Tome of Town Portal', unobtainable = true},
    {id = 142543, type = 'item', name = 'Scroll of Town Portal', unobtainable = true},
    {id = 28585, type = 'item', name = 'Ruby Slippers'},
    {id = 142298, type = 'item', name = 'Astonishingly Scarlet Slippers'},
    -- 8.2
    {id = 168907, type = 'toy', name = 'Holographic Digitalization Hearthstone'},
    -- 8.2.5
    {id = 172179, type = 'toy', name = 'Eternal Traveler\'s Hearthstone'},
    -- 9.0
    {id = 180290, type = 'toy', name = 'Night Fae Hearthstone'},
    {id = 182773, type = 'toy', name = 'Necrolord Hearthstone'},
    {id = 183716, type = 'toy', name = 'Venthyr Sinstone'},
    {id = 184353, type = 'toy', name = 'Kyrian Hearthstone'}
}
